INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Wolverine', '90', '1995', 'Marvel', 'Don\’t miss out! Sabretooth and Wolverine come to blows (and scratches), in a drag-out, no holds barred battle to the death. Wolvie may have gone too far, even by his own standards!', 'Penciller, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/0/4/36259-4250-40490-1-wolverine.jpg','Wolverine, Sabertooth', 'X-Men');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Wolverine', '93', '1995', 'Marvel', 'Beginning to slip into his old self, Wolverine goes out for a beer with New Mutant Cannonball. But a round of brews turns into a battle... against the Unstoppable Juggernaut! Cyber gets an early release from Muir Island.', 'Penciller, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/0/4/37019-4250-41414-1-wolverine.jpg','Wolverine, Juggernaut, Cyber', 'X-Men');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('All New Wolverine', '19', '2107', 'Marvel', 'Two words uttered that will forever change WOLVERINE\'s life... starting a non-stop race against a deadly transformative disease, a battle in a quarantined city and a mysterious villain with a target on her head.', 'Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/5786934-19.jpg', 'Wolverine, Laura', 'X-Men');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('All New Wolverine', '20', '2107', 'Marvel', 'WOLVERINE\'s got a brand-new suit, but she\'s the same claw-popping, sarcastic-quipping, efficient hero that we know and love. But now that the sickness is spreading, to what lengths will LAURA go to help the people in danger?', 'Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/5843217-20.jpg', 'Wolverine, Laura', 'X-Men');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Peter Parker: The Spectacular Spider-Man', '1', '2017', 'Marvel', 'The webslinging, wallcrawling wonder returns to New York City in the all-new PETER PARKER: THE SPECTACULAR SPIDER-MAN. A companion series to the best-selling Amazing Spider-Man series, Peter Parker is going back-to-basics for big heroics in the Big Apple. Featuring adversaries old and new, be there as Spider-Man returns to his friendly neighborhood for his never ending battle against crime and the dreaded "Parker Luck".', 'Artist, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/5914604-01.jpg', 'Spider-Man, Ant-Man, Black Widow, Captain America, Mason, Teresa Parker, Human Torch, Uatu Jackson', 'Avengers');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Amazing Spider-Man: Renew Your Vows', '1', '2017', 'Marvel', 'Continued from The Amazing Spider-Man Vol. 3. This is a five issue Secret Wars tie-in mini-series. Although this series takes place in an alternate reality, some plot-lines are continued into the ongoing The Amazing Spider-Man Vol. 4 series that starts right after this mini-series. This mini-series had a sequel named Amazing Spider-Man: Renew Your Vows Volume 2.', 'Artist, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/4598340-01.jpg', 'Spider-Man, Mary Jane, Annie Parker, Black Widow, Venom', 'Avengers');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Amazing Spider-Man: Renew Your Vows', '2', '2017', 'Marvel', 'SECRET WARS SERIES. Not even The Amazing Spider-Man is safe from Secret Wars! In this new Marvel Universe, Peter Parker, Mary Jane Watson and their daughter have to scrape by to make ends meet, but they have each other...', 'Artist, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/4672048-02.jpg', 'Spider-Man, Mary Jane, Annie Parker, Regent', 'Avengers');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Amazing Spider-Man: Renew Your Vows', '3', '2017', 'Marvel', 'SECRET WARS SERIES. The most controversial Spider-Man story of the year continues! There are some lines Spider-Man won\'t cross. Right?', 'Artist, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/4726122-03.jpg', 'Spider-Man, Mary Jane, Annie Parker, Regent', 'Avengers');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Amazing Spider-Man Renew Your Vows', '4', '2017', 'Marvel', 'SECRET WARS SERIES. To protect his family, Spider-Man takes the fight to the god-link REGENT! But that doesn\'t mean his daughter will sit back and let her dad have all the \"fun!\"', 'Artist, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/10/103431/4753080-04.jpg', 'Spider-Man, Mary Jane, Annie Parker, Regent', 'Avengers');

INSERT INTO books (title, issue, publish_date, publisher, synopsis, role, img_url, characters, teams) VALUES ('Amazing Spider-Man: Renew Your Vows', '5', '2017', 'Marvel', 'SECRET WARS SERIES. The Parkers vs. Regent.', 'Artist, Cover Artist', 'https://static.comicvine.com/uploads/scale_large/6/67663/4791314-05.jpg', 'Spider-Man, Mary Jane, Annie Parker, Regent', 'Avengers');

INSERT INTO artwork (books_id, format, page_num, img_url, description, feature) VALUES ('1', 'Wrap-Around', 'Cover', 'https://aworkingartist.com/images/wolverine_90_0_cover.jpg', 'Wrap-around cover on double 11x17 bristol board.  Pencils only. This cover was not inked.', 'Wolverine, Sabertooth');

INSERT INTO artwork (books_id, format, page_num, img_url, description, feature) VALUES ('1', 'Double-Page Spread', '1-2', 'https://aworkingartist.com/images/wolverine_90_1-2.jpg', 'Inked double-page spread.', 'Wolverine, Sabertooth');
